### ISSUE TITLE
Auto-GPT: Can't open main.py after install

### ISSUE THREAD

**Issue by hdroller** [diStyApps/seait#10]
I am getting the following error after installing Auto-GPT. I'm on 0.0.8 version of Seait. I have tried deleting the folder and reinstalling Auto-GPT but I still get that error.

E:\\seait.v0.0.8\\Auto-GPT\\scripts\\main.py': [Errno 2] No such file or directory

**Comment by diStyApps** [comment]
Thank you. 
Their installation changed; I'll release an update today.
