### ISSUE TITLE
Check for update does not update the app

### ISSUE THREAD

**Issue by hdroller** [diStyApps/seait#12]
When checking for update, the app says No update is available and that the latest version is 0.0.8.

![image](https://user-images.githubusercontent.com/62087201/233223090-d14c9b74-e9a5-4dc9-a8e4-e3607573a146.png)

**Comment by hdroller** [comment]
Also, after updating to 0.0.9, it says there's a new version.
![image](https://user-images.githubusercontent.com/62087201/233223301-bf65d168-e2a4-41ec-9d5d-d547703bc05e.png)

**Comment by diStyApps** [comment]
Thank you very much ill fix it.
