### ISSUE TITLE
[Bug] v0.1.1 "Project cannot contain spaces, project ID X not found"

### ISSUE THREAD

**Issue by DarkVamprism** [diStyApps/seait#14]
Running the tool works fine, but clicking on any of the tools available I get a looping error with `Path cannot contain spaces, project ID X not found` that causes the GUI to reload, and repeat, if I click a second project it will loop between the GUIs.

I ran seait from a path that does include a space and if I initially run it in a no space path then itll work(except trying to set the path to one without spaces) and I know that is a workaround but id rather have this program put in a place I want it rather than be confined to a no space path.

**Comment by diStyApps** [comment]
Thank you, fixed GUI reload, right now i am also confined by dependencies that don't support spaces in path, i will put more focus on that in the future updates.
