### ISSUE TITLE
Access denied.

### ISSUE THREAD

**Issue by atheran2** [diStyApps/seait#17]
https://gyazo.com/af5179aae1d55fbc72d9249bb2245a03

I run as admin, checked folder permissions..I've no idea how to tackle this.

Win11 if that matters.

**Comment by diStyApps** [comment]
Try moving the installation from the desktop to another folder, such as c:\ai_tools\seait, and then try again.

**Comment by atheran2** [comment]
> Try moving the installation from the desktop to another folder, such as c:\ai_tools\seait, and then try again.

Nope. Put it on C:\seait, still the same error. :(

**Comment by ashledombos** [comment]
It may be an antivirus a security software that added some SRP (Software Restriction Policies) or more recently AppLocker restrictions. Maybe you should have a look at Event Viewer and look for AppLocker alerts (or alerts with 865 866 ID for former SRP settings). Maybe also have a look at your third party security software if you have one.

**Comment by diStyApps** [comment]
Try the new install.
