### ISSUE TITLE
Arguments extra options

### ISSUE THREAD

**Issue by Tobe2d** [diStyApps/seait#19]
Could you add more Arguments for vladmandic? 

--api

Maybe just like how the other UI-UK - A1111 fork you added from anapnoe

The other thing, If can you also add option where we can add other things to the webui-user.bat it will be great.
example:
--opt-sdp-attention

While some other extentions need to set model location just like SADTALKER extention

example:
set SADTALKER_CHECKPOINTS=E:\stable-diffusion-webui\extensions\SadTalker\checkpoints

And some people like to stay up to date so we can add:
git pull

but each of those goes into its line of code.

Hope what I say make some sense ;-)

**Comment by diStyApps** [comment]
Hey, thank you for using seait.

At the bottom of the Actions section, there is an update button that perform git pull.

![Screenshot 2023-04-29 195223](https://user-images.githubusercontent.com/3084832/235314422-72ff5fad-5f75-4801-887e-d79c40439b64.jpg)

In vladmandic's fork, the --api argument has been changed from the original project. I can add: --api-auth u555:p444 and --opt-sdp-attention, which I forgot. In the future, I will let users add whatever they want, but if the argument does not exist in the project, it will cause the project to crash.

Regarding the set arguments, there are a few approaches to launching. Currently, seait launches via the launch.py script, which ignores settings and arguments from webui-user.bat. However, I have done tests and, in some versions, it was launched via webui.bat, which will use the arguments in webui-user.bat but may cause other issues. There are also other approaches, so it is not an optimal implementation yet, but it just works for now.

So I might add an internal way to add set arguments, such as set PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.6,max_split_size_mb:128 and what you presented, or let the user choose how they want to launch the project.

There are a lot of features and improvements that can be added to this project, but it takes time. I wish I could focus only on this project.

Thank your suggestions.
