### ISSUE TITLE
add to automatic1111 launcher argument --theme=dark or it could better add a textfield to launcher where users can write custom arguments

### ISSUE THREAD

**Issue by DocZ80** [diStyApps/seait#2]
Add to automatic1111 launcher argument --theme=dark or it could be better add a textfield to launcher where users can write custom arguments

**Comment by diStyApps** [comment]
I will add custom arguments but meanwhile i have added --theme=dark .

**Comment by DocZ80** [comment]
Thank you, cool project

**Comment by diStyApps** [comment]
Thank you.
