### ISSUE TITLE
[feature request]Specify the corresponding venv directory or start exe

### ISSUE THREAD

**Issue by sdbds** [diStyApps/seait#20]
thank u for great work！
some tools have WindowsVersion so use python or exe such as your Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI or comfyui for Windows...
can we specify  for them?
and many sd-webui venv can use both,i want to special a General Version

**Comment by diStyApps** [comment]
Hey thank you very much using my projects.
That good point all add support for exe.
you can use same venv on multi project using the symlink creator tool.
