### ISSUE TITLE
Symlink Windows UAC protection

### ISSUE THREAD

**Issue by MojiMojiMu** [diStyApps/seait#21]
Hi
By default you cannot create symbolic links for models right away because of Windows security. 
Running the program as an administrator does not solve the problem either. 
I think you need to add this information either in the program or in the readme

You have to add user rights following this instruction: 
Open gpedit.msc
Computer Configuration\Windows Settings\Security Settings\Local Policies\User Rights Assignment\Create symbolic links
Type the user name and click “Check Names” then OK.
Reboot the computer

**Comment by diStyApps** [comment]
Thank you very much sorry i missed that, i always turn it off on my machines. not recommend to do.
ill add your instructions and later on ill add a script for that.

**Comment by ashledombos** [comment]
There should be another alternative for people with Windows 10/11 Family (no GPedit)

**Comment by ashledombos** [comment]
Couldn’t it be possible to use instead a self elevating script such as this one ? https://stackoverflow.com/a/27083780 

Tested on my side, it works correctly.

**Comment by diStyApps** [comment]
Wow thank you very helping make the seait better, I Also wrote something. for reg, ill test your script and if its worked better ill add it.

**Comment by diStyApps** [comment]
Thank you added your script, tested on windows 10 home.
