### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application 

### ISSUE THREAD

**Issue by AgentE24** [diStyApps/seait#24]
Unable to install SEAIT due to this error:
![error message](https://user-images.githubusercontent.com/62515329/235847602-5f194246-3825-4024-ad71-7b57109afd6b.png)
I have tried uninstalling visual studio and python and reinstalling python. I have tried rolling back to version 0.1.3 (the current version as of writing is 0.1.4). 

Windows 10 Pro x64 22H2

**Comment by diStyApps** [comment]
Hey,
Do any other versions work for you?
Which Python version are you using? Is it 32-bit or 64-bit?
Also, did you use the Python installer that comes with seait?

**Comment by AgentE24** [comment]
I refreshed windows, and it seems to be working now
