### ISSUE TITLE
not able to downgrade git !!

### ISSUE THREAD

**Issue by mrbeandev** [diStyApps/seait#27]
i installed Viadiffusion - A1111 and not able to downgrade it to the a older commit as the new commit is having some issues

**Comment by diStyApps** [comment]
Didn't added yet.
For now try:

To activate the environment in any project, be in the root folder.

`For example: C:\DEMO\seait\automatic`

Type CMD in the Navigation bar.

Then type: 
```
venv\Scripts\activate
```

For example: `C:\DEMO\seait\automatic>venv\Scripts\activate`

After the environment is activated, it should look like this:

(venv) C:\DEMO\seait\automatic>automatic\Scripts\activate

And then type git checkout for example :
```
git checkout commit 9b6133bc98337f2f7a24a63cd616b2839308010
```
