### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by aasonacademy** [diStyApps/seait#28]
i dont know where to put openai api key (tying to install autogpt)

**Comment by aasonacademy** [comment]
well i just created now txt file and pasted "OPENAI_API_KEY="xxx" after that i've change the .txt in to.env i guess its working now !

**Comment by diStyApps** [comment]
Great, also in Auto-GPT folder you have file .env.template rename it to .env there you have all the options
https://github.com/Significant-Gravitas/Auto-GPT/blob/master/.env.template
