### ISSUE TITLE
Can't get it to run

### ISSUE THREAD

**Issue by Grupletruge** [diStyApps/seait#31]
IT creates preference files and then the Commandline window crashes. same for 1.3.
I have a1111 installed, possible issue?

**Comment by diStyApps** [comment]
Hey, A screenshot  or error log will help me, also did you try [SEAIT 0.1.4.5](https://www.patreon.com/posts/seait-0-1-4-5-82995978) ? , its free and include new installation method.

**Comment by diStyApps** [comment]
Try the new install version
