### ISSUE TITLE
Update "Vladiffusion"

### ISSUE THREAD

**Issue by Aptronymist** [diStyApps/seait#33]
Hi, you've got a great app! Used it a few times to install text gen webui.

Just wanted to let you know to please change the "Vladiffusion - A1111 fork" to "SD.Next: Stable Diffusion Evolved", as that has never been its name, and it can't even rightly be called a fork at this point.

Thanks!

**Comment by diStyApps** [comment]
Ok thank you, ill do it.

**Comment by diStyApps** [comment]
Updated.
