### ISSUE TITLE
[Issue] error when running 

### ISSUE THREAD

**Issue by zethfoxster** [diStyApps/seait#35]
ModuleNotFoundError: No module named 'pytorch_seed'

trying to install bark gui.

**Comment by Helge666** [comment]
I have the same issue:

bark-gui Instructed installation completed
Traceback (most recent call last):
  File "D:\Software\seait\bark-gui\webui.py", line 11, in <module>
    import pytorch_seed
ModuleNotFoundError: No module named 'pytorch_seed'

This is my first attempt to use SEAIT. Not a really off to a great start here :-/

**Comment by diStyApps** [comment]
its only happens on bark?

**Comment by taxmaan** [comment]
I also have the same issue

**Comment by diStyApps** [comment]
Fixed: https://github.com/diStyApps/seait/releases/download/0.1.4.7/seait.0.1.4.7_b_fix_setup.exe.zip

**Comment by AsaTyr2018** [comment]
@zethfoxster @Helge666 @taxmaan 
can you please test the fix and give a small feedback if the issue still appear? =) Thank you

**Comment by AsaTyr2018** [comment]
I Close this Ticket for now. In case this Problem Reaccure, Please open a new Ticket.
