### ISSUE TITLE
How to Stop an AI

### ISSUE THREAD

**Issue by AsaTyr2018** [diStyApps/seait#36]
Just curious.
Since all AI´s are loaded in the same CMD Window. How can i stop an AI if i don´t need it anymore seperatly?
I don´t see any "Stop" Button ^^

**Comment by AsaTyr2018** [comment]
okay. for what purpose is this "AiPanic" button?

**Comment by diStyApps** [comment]
Well i guess when the day will come maybe it is the way to "How to Stop an AI".
