### ISSUE TITLE
[Issue] AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by MrBoden** [diStyApps/seait#37]
For some reason none of the installs want to play with my 4070. I thought there might be a command line arg or setting, but I'm not sure how to resolve this.

**Comment by diStyApps** [comment]
Add a log or a screenshot please.

**Comment by AsaTyr2018** [comment]
@MrBoden anything new here? can you add some console logs or screenshots please?

If everything is fine, please close the issue.
