### ISSUE TITLE
Python does not install properly

### ISSUE THREAD

**Issue by meerpack** [diStyApps/seait#38]
![image](https://github.com/diStyApps/seait/assets/14966598/ca87bc06-164c-4fd3-a932-51667c9891ce)
I tried installing python using this tool and it says it was successful. However, when launching Visioncrafter, it now states python is not installed and will not install from the store.

**Comment by meerpack** [comment]
python is already installed
![image](https://github.com/diStyApps/seait/assets/14966598/775366d6-abab-45d2-9f4c-759af8536b7b)

**Comment by diStyApps** [comment]
All seems fine, Try to uninstall python and install it again, and tell me if it worked.

**Comment by meerpack** [comment]
It did not work. I have tried with two different python version, both clean installs, and neither worked. Same error as above.

**Comment by AsaTyr2018** [comment]
open your cmd and just launch "python"
what does it tells you? If you installed several Versions. it might Conflict in your PATH settings.

**Comment by Fearganainim** [comment]
Having same issue. No matter how many times I install python SEAIT won't recognize it.

**Comment by diStyApps** [comment]
Thank you [Fearganainim](https://github.com/Fearganainim)
For users encounter this issue try this: https://www.youtube.com/watch?v=EqhSXC1XfWM
