### ISSUE TITLE
[Feature Request] Easy Lora Training Script

### ISSUE THREAD

**Issue by AsaTyr2018** [diStyApps/seait#40]
Hey there,

since you include Kohyas Gui.
You might care to Include the Easy Lora Trainer too?

https://github.com/derrian-distro/LoRA_Easy_Training_Scripts

I use it a lot for Training my Loras

**Comment by diStyApps** [comment]
Very nice i will check it out, any benefits on kohya gui except the qt GUI?

**Comment by AsaTyr2018** [comment]
> Very nice i will check it out, any benefits on kohya gui except the qt GUI?

The Main Benefit is that it makes a lot of workflows easyer and allow to queue up multiple training jobs. 
Like you can set up 10-20 lora trainings and leave the computer running ^^ 

check my civitai models. they all maid with this trainer: https://civitai.com/user/AsaTyr/models

**Comment by diStyApps** [comment]
Oh wow the queue up will be great, Yes i am following you on civit, very cool artwork, ill try some of your lora's soon.

**Comment by AsaTyr2018** [comment]
> Oh wow the queue up will be great, Yes i am following you on civit, very cool artwork, ill try some of your lora's soon.

Please do and share some of your art with me =D

**Comment by AsaTyr2018** [comment]
@diStyApps works charming. i love it =D Thank you!
