### ISSUE TITLE
[Bug]: InvokeAI Installation or Launch failed

### ISSUE THREAD

**Issue by H1ghSyst3m** [diStyApps/seait#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Bug Description

```
launching InvokeAI at C:\Users\H1ghSyst3m\seait\InvokeAI
C:\Users\H1ghSyst3m\seait\InvokeAI\venv\Scripts\python.exe: can't find '__main__' module in 'C:\\Users\\H1ghSyst3m\\seait\\InvokeAI\\invokeai'

(venv) C:\Users\H1ghSyst3m\seait\InvokeAI>
```

### Step-by-step instructions to reproduce the issue.

Install InvokeAI and launch

### Expected Behavior

It launches and works

### Current Behavior

After I start the installation

the Error.
```
launching InvokeAI at C:\Users\H1ghSyst3m\seait\InvokeAI
C:\Users\H1ghSyst3m\seait\InvokeAI\venv\Scripts\python.exe: can't find '__main__' module in 'C:\\Users\\H1ghSyst3m\\seait\\InvokeAI\\invokeai'

(venv) C:\Users\H1ghSyst3m\seait\InvokeAI>
```

appeared, but in SEAIT it shows that is installed and ready to launch. On launch the same error

### Version or Commit where the problem happens

0.1.4.7

### What platforms do you use SEAIT ?

Windows

### What Python version are you running on ?

3.10.6

### What proccecor do you running on SEAIT ?

GPU, CPU

### What GPU are you running SEAIT on?

3090 Ti

### On what Project the issue are you facing?

InvokeAI

### Console logs

```Shell
launching InvokeAI at C:\Users\H1ghSyst3m\seait\InvokeAI
C:\Users\H1ghSyst3m\seait\InvokeAI\venv\Scripts\python.exe: can't find '__main__' module in 'C:\\Users\\H1ghSyst3m\\seait\\InvokeAI\\invokeai'

(venv) C:\Users\H1ghSyst3m\seait\InvokeAI>
```

**Comment by diStyApps** [comment]
Fixed check it out.

**Comment by AsaTyr2018** [comment]
> ### Is there an existing issue for this?
> 
>     * [x]  I have searched the existing issues and checked the recent builds/commits
> 
> 
> ### Bug Description
> 
> ```
> launching InvokeAI at C:\Users\H1ghSyst3m\seait\InvokeAI
> C:\Users\H1ghSyst3m\seait\InvokeAI\venv\Scripts\python.exe: can't find '__main__' module in 'C:\\Users\\H1ghSyst3m\\seait\\InvokeAI\\invokeai'
> 
> (venv) C:\Users\H1ghSyst3m\seait\InvokeAI>
> ```
> 
> ### Step-by-step instructions to reproduce the issue.
> 
> Install InvokeAI and launch
> ### Expected Behavior
> 
> It launches and works
> ### Current Behavior
> 
> After I start the installation
> 
> the Error.
> 
> ```
> launching InvokeAI at C:\Users\H1ghSyst3m\seait\InvokeAI
> C:\Users\H1ghSyst3m\seait\InvokeAI\venv\Scripts\python.exe: can't find '__main__' module in 'C:\\Users\\H1ghSyst3m\\seait\\InvokeAI\\invokeai'
> 
> (venv) C:\Users\H1ghSyst3m\seait\InvokeAI>
> ```
> 
> appeared, but in SEAIT it shows that is installed and ready to launch. On launch the same error
> ### Version or Commit where the problem happens
> 
> 0.1.4.7
> ### What platforms do you use SEAIT ?
> 
> Windows
> ### What Python version are you running on ?
> 
> 3.10.6
> ### What proccecor do you running on SEAIT ?
> 
> GPU, CPU
> ### What GPU are you running SEAIT on?
> 
> 3090 Ti
> ### How much GPU VRAM are you running SEAIT on?
> 
> _No response_
> ### On what Project the issue are you facing?
> 
> InvokeAI
> ### Console logs
> 
> ```shell
> launching InvokeAI at C:\Users\H1ghSyst3m\seait\InvokeAI
> C:\Users\H1ghSyst3m\seait\InvokeAI\venv\Scripts\python.exe: can't find '__main__' module in 'C:\\Users\\H1ghSyst3m\\seait\\InvokeAI\\invokeai'
> 
> (venv) C:\Users\H1ghSyst3m\seait\InvokeAI>
> ```
> 
> ### Additional information
> 
> _No response_

Is the Issue still Active or has it been solved?

**Comment by H1ghSyst3m** [comment]
I tested it right now. The Issue is solved. Installation worked.
