### ISSUE TITLE
[Bug]: WhisperUI does not start.

### ISSUE THREAD

**Issue by Microturbine** [diStyApps/seait#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Bug Description

When installing WhisperUI and trying to start it, an error occurs and it does not start.

C:\Users\Myname\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'C:\\Users\\Myname\\seait\\whisper-ui\\streamlit': [Errno 2] No such file or directory

### Step-by-step instructions to reproduce the issue.

Just install WhisperUI.

### Expected Behavior

Starting WhisperUI.

### Current Behavior

C:\Users\Tux55\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'C:\\Users\\Tux55\\seait\\whisper-ui\\streamlit': [Errno 2] No such file or directory

(venv) C:\Users\Tux55\seait\whisper-ui>

### Version or Commit where the problem happens

seait 0.1.4.8

### What platforms do you use SEAIT ?

Windows

### What Python version are you running on ?

python 3.11.5

### What proccecor do you running on SEAIT ?

GPU

### What GPU are you running SEAIT on?

GTX１６６０

### On what Project the issue are you facing?

WhisperUI

### Console logs

```Shell
C:\Users\Tux55\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'C:\\Users\\Tux55\\seait\\whisper-ui\\streamlit': [Errno 2] No such file or directory

(venv) C:\Users\Tux55\seait\whisper-ui>
```

**Comment by AsaTyr2018** [comment]
Hey there,

did you check if this folder exist?
C:\Users\Tux55\seait\whisper-ui\streamlit
This Error tells that it can´t locate the folder. ([Errno 2] No such file or directory)

Also try to change the default folder away from your user directory. 
![grafik](https://github.com/diStyApps/seait/assets/43162495/0376dd27-a21b-43cb-a392-7ef0c354a1bd)

Just for Testing Purpose.

**Comment by AsaTyr2018** [comment]
@Microturbine correction. i see the issue. just tested myself. no need to change the directory ^^ 

@diStyApps  you might look into this. the Path used by the script changed and mutated. 
Git Clone runs smoothly but once its downloaded and try to start it adds double slashes in the path. Resulting in Error 2 File not found. Happens in Users Directory and also in any other directory (My test was D:\AI\Whisper)
