### ISSUE TITLE
ERROR:root:Error getting NVIDIA GPU info: Not Supported

### ISSUE THREAD

**Issue by VelvetAcidChrist** [diStyApps/seait#6]
I gave access to the GP performance counters to all users, I tried to run seait.exe with administrator rights, the error still does not disappear. The program itself is in the root of the SD folder, but thinks it is not installed, AiPanic and Settings tabs are inactive. What can be the problem?

**Comment by diStyApps** [comment]
What GPU you got ? 
I think Its just error for GPU reading System monitor stats, ill fix it, and you still can install for example auto1111,
some scripts GPU Access denied even with administrator rights, on my 970 works properly on 3080 it complains,
ill make it optional till i sort it out.

For Launching existing installation seait.exe should be outside of the root of the SD folder and make sure its called stable-diffusion-webui till ill add custom folder selection.

Launching existing installation might work, but if it wont, Delete venv and create it again it should work, careful it will delete dependencies, and be careful with uninstall button. 

"AiPanic and Settings" not implemented yet sorry for the confusion.

**Comment by VelvetAcidChrist** [comment]
>

I have GTX 1050 Ti (4Gb). About installing auto1111 - I already have it installed and working. Moved the program to D:/Seait/, but unfortunately nothing has changed.

In fact, I have a feeling that I misunderstood the purpose of the program and I don't really need it because Auto1111 has been on my computer for a long time :) I thought the utility was adding some new repositories with extensions for SD.

**Comment by Teie** [comment]
Hi.
Does everyone agree to close the topic?

**Comment by VelvetAcidChrist** [comment]
Yes

**Comment by diStyApps** [comment]
Issue fixed 
and It does adds some new repositories with extensions for SD, like controlnet that includes the models, and dreambooth for smoother installation, but main purpose is to add more projects.

dir should be like this

├── D:/somedir
 │   ├──seait.exe 
 │   └── stable-diffusion-webui
 │   └── InvokeAI
 │   └── ComfyUI
