### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Makon30** [diStyApps/seait#7]
Since the last few updates I am getting this when trying to launch SD:

_launching stable-diffusion-webui
command run and script run
'J:\Super' is not recognized as an internal or external command,
operable program or batch file.

J:\Super Easy AI Installer Tool\stable-diffusion-webui>_

**Comment by Loflou** [comment]
same, i'm getting a similar error message.

**Comment by diStyApps** [comment]
There is an issue with the file path due to the presence of spaces in the folder names. I will fix it soon. Meanwhile, please use the following file path instead of the original one:

J:\Super_Easy_AI_Installer_Tool\stable-diffusion-webui

**Comment by diStyApps** [comment]
#14
